YOUTUBE = {
    '1': '_rdv4jM4q18',
    '2': 'R8mb9eqkyBA',
    '3': 'UgBJ0qzUfFI',
    '4': 'yYpM5UQad8E',
    '5': 'Q9RTaClxJ4I',
    '6': 'oPJEkoyH74w',
    '7': '_rBTrh-vwTc',
    '8': 'DPscSVEby6E',
    '9': 'jGg2pxO2dJc',
    '10': 'gAfFUwoGRfs',
    '11': 'fu_dPg9gH2I',
}

def A(kicker, headline, deck, takes, body):
    return {'kicker': kicker, 'headline': headline, 'deck': deck, 'takeaways': takes, 'body': body}

ARTICLES = {
    '1': A('Series premiere', 'What it actually takes to run a construction business',
        'Jake and Daniel open the show with 3:20am alarms, boxing before site, and the gap between a finished tower and the people who built it.',
        ['Both hosts started around 14 and never left the tools far behind.', 'Facades reward people who can hold a standard when the crane is booked and the drawings no longer match the slab.', 'Hard conversations inside a business are not optional.', 'Marketing, AI and apprentices are already changing who gets hired.'],
        '<p>Episode 1 is the origin story. Jake Gorry from Proline Group and Daniel Alizzi from Complex Facade Install sit down without a guest and talk about the part of construction most people never see.</p><p>The finished building is the easy photograph. Behind it is the early alarm, the family you are trying not to short-change, and the decision to stay in an industry that chews people up.</p>'),
    '2': A('Leadership on site', 'The warning signs every construction leader is ignoring',
        'Fresh off a 9.7-tonne panel install that had to be replanned on the crane.',
        ['Complex jobs fall over when the plan cannot be torn up in real time.', 'Culture is who stays when the job gets ugly.', 'Writing leadership standards down changes how a team behaves.'],
        '<p>Episode 2 opens on 9,700 kilo concrete panels and a method rewritten on the crane. Jake talks about writing a leadership book for his team. Daniel talks about crews that can think when the sequence dies.</p>'),
    '3': A('Family and the firm', 'Family in business is an advantage only if the standard is higher',
        'Loyalty is not a substitute for performance.',
        ['Family can be the greatest asset or the thing that sinks a company.', 'Weekly job data beats monthly reporting.', 'Leaders built from within usually outlast leaders bought in.'],
        '<p>Episode 3 is standards, loyalty and the long game. When the person on the tools is also family, the companies that last raise the bar rather than lower it.</p>'),
    '4': A('How work is actually won', 'Relationships in construction are a track record.',
        'Jobs do not go to whoever knows the right PM.',
        ['Work is won by people who deliver, then get called again.', 'Knowing the right person is worthless if the last job was a mess.'],
        '<p>The subbies who keep getting the call finished the last job clean, told the truth when it went wrong, and made the builder look good in front of the client.</p>'),
    '5': A('The pipeline', 'The next wave of Australian construction will punish unprepared subcontractors',
        'The industry is about to get busier than most businesses are built for.',
        ['Capacity has to be built before the work arrives.', 'Winners of the next five years will already have invested in people and plant.'],
        '<p>Episode 5 is the show\'s most watched conversation. The next cycle will pay the businesses that already trained people and stopped pretending a busy diary is a strategy.</p>'),
    '6': A('Guest: Adam Hall', 'Adam Hall on bankruptcy, fences, and building a national contracting brand',
        'The first guest is Managing Director of AH Fencing.',
        ['Adam and Matt Carroll started AH Fencing after years on commercial fencing sites.', 'The early years lost money. The later years built a multi-city contractor.'],
        '<p>Adam Hall built AH Fencing with schoolmate Matt Carroll in 2017. He talks bankruptcy, the first two years that did not make money, and the difference between a fencing crew and a company that can run hundreds of commercial jobs a year.</p>'),
    '7': A('Time on site', 'Australian construction is too slow for what is coming',
        'Wasted hours and the cost of pretending a late programme is just how the industry works.',
        ['Time is the most expensive material on a facade package.', 'Most delays are decisions made too late.'],
        '<p>Episode 7 is wasted time: sequences that only exist on a Gantt chart, crane days that die because one trade was not ready.</p>'),
    '8': A('Technology on site', 'Most construction businesses are five years behind and do not know it',
        'AI, software and the gap between available tools and how most subcontractors still run a job.',
        ['The technology already exists. Adoption is the bottleneck.', 'AI will not replace a good leading hand. It will expose a sloppy office.'],
        '<p>If you cannot see the job in real time, you are guessing with other people\'s money. Pair this with episode 11.</p>'),
    '9': A('Quiet markets', 'How to use a slow period without wrecking the business',
        'When the phone is quieter, the temptation is cheap work.',
        ['Chasing cheap jobs trains the market to pay you less later.', 'The advantage is built in the quiet and spent in the rush.'],
        '<p>Episode 9 is for the weeks when every conversation starts with keeping the boys going. The worst thing you can do is teach clients that you will buy work.</p>'),
    '10': A('Guest: Ethan Chittick', 'Ethan Chittick on commercial carpentry, culture and a production-line site',
        'Why the best installer is not automatically the next leading hand.',
        ['Ethan started young and built a serious Melbourne carpentry operation before 30.', 'The best tradesperson is often a poor default choice for leadership.'],
        '<p>Ethan Chittick is Director of Commercial Carpentry and co-founder of B&E Built. He left school in Year 11 and started at 21.</p>'),
    '11': A('Guest: Damien Quinn', 'Damien Quinn left Multiplex to build Visibuild. The site never left him.',
        'Fifteen years with one of Australia\'s biggest builders, then a software company.',
        ['Damien spent about 15 years at Multiplex including Sapphire Apartments, Shangri-La and Monash.', 'Visibuild is used on large Australian projects including data centres.'],
        '<p>Damien Quinn is co-founder and CEO of Visibuild. He left Multiplex because quality tools on site were still paper and hope. Visibuild later raised $6.6 million from Skip Capital.</p>'),
}
